# fastlane Fastfile for poke_discoverer
# See https://docs.fastlane.tools/actions/ for more options

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Builds the release APK"
  lane :build do
    gradle(task: "assembleRelease")
  end
end
